= Curso de Desarrollo / Micronaut
IES Systems <isidoro.trevino@ies-systems.com>
2019-08-06
:revnumber: {project-version}
:example-caption!:
ifndef::imagesdir[:imagesdir: images]
ifndef::sourcedir[:sourcedir: ../java]

== Cliente HTTP

* Brinda la posibilidad de invocar a otros microservicios
* Permite la creación de clientes dinámicos a partir de una interface

[source,java]
----
public interface ProductoOperations{
	Flowable<Producto> consultarProductos();
}
----

=== Cliente HTTP

* Se crea otra interface a la que se asigna un annotation para crear un 
cliente dinámico

[source,java]
----
@Client("http://localhost:8081") 
public interface ProductoClient extends ProductoOperations {

    @Get("/producto")
    Flowable<Producto> findAll();
}
----

=== Cliente HTTP

==== DEMO

== Service Discovery

* Habilidad de los microservicios de encontrarse sin conocer la ubicación 
física o la dirección IP de los mismos
** De manera manual mediante DNS
** Mediante servidores de descubrimiento como Consul, Zookeeper o Eureka
** Delegando la labor al contenedor, por medio de Kubernetes o Swarm

=== Consul

* Servidor de descubrimiento de servicios
** Revisión de salud
** Almacenamiento de llaves clave-valor
** Soporte multi-datacenter

=== Integración Micronaut / Consul

[source,groovy]
.build.gradle
----
compile "io.micronaut:micronaut-discovery-client"
----

[source,yaml]
.application.yml
----
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
----

=== Integración Micronaut / Consul

* Se actualizan los "Clientes HTTP", cambiando las ip's por nombres de servicio

[source,java]
----
@Client("http://localhost:8081") 
public interface ProductoClient extends ProductoOperations
---- 

* Por:

[source,java]
----
@Client("producto") 
public interface ProductoClient extends ProductoOperations
---- 

=== Integración Micronaut / Consul

==== DEMO

[source,text]
----
$ docker run -p 8500:8500 consul
----

== Rastreo Centralizado

* Presenta retos especiales en las arquitecturas distribuidas
* Existen sistemas de rastreo distribuido que mitigan la problemática
** Zipkin
** Jaeger
* Estándar **OpenTracing**

=== Conceptos

* **Span** -> Bloque primario de un rastreo distribuido
** Unidad de trabajo individual en un sistema distribuido
* **Tag** -> Anotaciones llave valor que se agregan a un span

=== Integración con Micronaut

[source,groovy]
.build.gradle
----
runtime 'io.zipkin.brave:brave-instrumentation-http'
runtime 'io.zipkin.reporter2:zipkin-reporter'
compile 'io.opentracing.brave:brave-opentracing'
----

=== Integración con Micronaut

[source,java]
.application.yml
----
tracing:
    zipkin:
        http:
            url: http://localhost:9411
        enabled: true
----

=== Rastreo Centralizado

==== DEMO

[source,text]
----
$ docker run -d -p 9411:9411 openzipkin/zipkin
----

== MyBatis

* Framework de persistencia orientado a facilitar la ejecución de 
consultas
* Patrón de diseño SQL - Mapper
** Permite la ejecución de sentencias SQL complejas
** Disminuye los riesgos de SQL Injection (entre otros)

=== Uso

* Agregar dependencia

[source,groovy] 
----
compile group: 'org.mybatis', name: 'mybatis', version: '3.4.6'
compile "io.micronaut.configuration:micronaut-jdbc-hikari"
compile group: 'org.postgresql', name: 'postgresql', version: '42.2.5'
----

=== Configuración

* Configuración General

[source,java]
----
TransactionFactory transactionFactory = new JdbcTransactionFactory();
Environment environment =
        new Environment("production", transactionFactory, dataSource);
Configuration configuration = new Configuration(environment);
----

=== Configuración

[source,java]
----
InputStream inputStream = Resources.getResourceAsStream(mapperResource);
XMLMapperBuilder mapperParser = new XMLMapperBuilder(inputStream, configuration, mapperResource, configuration.getSqlFragments());
mapperParser.parse();
----

=== Mappers

[source,xml]
----
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.ies.curso.dia5.PruebaReactive">
     .....
</mapper> 
----

=== MyBatis

==== DEMO

