/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ies.curso.ext;

import com.google.common.collect.BiMap;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	
    	
        System.out.println(new App().getGreeting());
        
        System.out.println("Classloader of Main:"
		        + App.class.getClassLoader());
		System.out.println("Classloader of String:"
		        + String.class.getClassLoader());
		System.out.println("Classloader of BiMap:"
		        + BiMap.class.getClassLoader());
    }
}
